### ISSUE TITLE
PMTs and miner incentives 

### ISSUE THREAD

**Issue by ursuscamp** [LNP-BP/layer1#4]
This is a very intriguing idea. A question I have of miner incentives: If mining is permissionless, what stops miners from deciding to not release PMTs? If there are gigabytes of PMTs for every header, why wouldn’t a miner just mine a new header to collect fees, then just not push the PMTs?

**Comment by ursuscamp** [comment]
Never mind, this was addressed on Twitter: https://twitter.com/lnp_bp/status/1664973049295257605

**Comment by Nuhvi** [comment]
This is an important question and needs to be addressed here. DA is the hardest part always. And the twitter link points to a hand wavy reference to crypto economics ... which doesn't say much.

Is there an update on this?
